#!/usr/bin/env python3
"""Extract the token definitions from kawaii-meadow's core.css.

The app maps kawaii-meadow's role tokens onto its own --pm-* roles; it never uses
the kit's component classes. Importing the whole of core.css therefore adds ~40
component rulesets we do not want, and two of them (.tab, .tab-bar) collide with
class names the app already uses — which restyled the app's tab bar in every
theme, Default included.

So we import only the rules that define custom properties. Regenerate after
updating the vendored core.css:

    python3 tools/extract-km-tokens.py

Source:  src/themes/kawaii-meadow-core.css   (vendored unmodified)
Output:  src/themes/kawaii-meadow-tokens.css (generated; do not hand-edit)
"""

import pathlib
import re
import sys

SRC = pathlib.Path("src/themes/kawaii-meadow-core.css")
OUT = pathlib.Path("src/themes/kawaii-meadow-tokens.css")


def split_rules(css: str):
    """Yield (selector, body) for each top-level rule, tracking brace depth."""
    i, depth, start = 0, 0, 0
    while i < len(css):
        ch = css[i]
        if ch == "{":
            if depth == 0:
                selector = css[start:i].strip()
                body_start = i + 1
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                yield selector, css[body_start:i]
                start = i + 1
        i += 1


def only_custom_properties(body: str) -> bool:
    """True when every declaration in the body is a custom property."""
    # Nested blocks (a @media arm) are handled by the caller, not here.
    if "{" in body:
        return False
    decls = [d.strip() for d in body.split(";") if d.strip()]
    if not decls:
        return False
    return all(d.startswith("--") for d in decls)


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1

    css = re.sub(r"/\*.*?\*/", "", SRC.read_text(), flags=re.S)

    kept, dropped = [], 0
    for selector, body in split_rules(css):
        if selector.startswith("@media"):
            inner = [
                f"  {sel} {{{b.rstrip()}\n  }}"
                for sel, b in split_rules(body)
                if only_custom_properties(b)
            ]
            if inner:
                kept.append(f"{selector} {{\n" + "\n".join(inner) + "\n}")
            continue
        if selector.startswith("@"):
            dropped += 1
            continue
        if only_custom_properties(body):
            kept.append(f"{selector} {{{body.rstrip()}\n}}")
        else:
            dropped += 1

    header = (
        "/* GENERATED by tools/extract-km-tokens.py — do not edit.\n"
        " *\n"
        " * kawaii-meadow's token definitions only. Its component classes are left\n"
        " * out on purpose: the app uses its own components, and the kit's .tab and\n"
        " * .tab-bar would otherwise restyle the app's tab bar in every theme.\n"
        " */\n\n"
    )
    OUT.write_text(header + "\n\n".join(kept) + "\n")
    print(f"kept {len(kept)} token rules, dropped {dropped} component rules -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
